steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sample_app:$SHORT_SHA'
      - -f
      - ./api/Dockerfile
      - --build-arg  
      - _DB_HOST=$_DB_HOST
      - --build-arg 
      - _DB_DATABASE=$_DB_DATABASE
      - --build-arg 
      - _DB_USER=$_DB_USER 
      - --build-arg 
      - _DB_PASSWORD=$_DB_PASSWORD
      - --build-arg
      - _DB_PORT=$_DB_PORT
      - './api'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'do pushing image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sample_app:$SHORT_SHA'
      
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'do deploying'
    args:
    - 'run'
    - 'deploy'
    - 'go-api'
    - '--image=gcr.io/$PROJECT_ID/sample_app:$SHORT_SHA'
    - '--region=us-central1'
    - '--project=tech-lab-323207'
